lab2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from myapp import views as myapp_view
##lab5 group2 pangfan 104439988 liulei 104651816
urlpatterns = [
    url(r'^$', myapp_view.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^myapp/', include('myapp.urls', namespace='myapp')),
]

myapp/urls.py
##lab5 group2 pangfan 104439988 liulei 104651816

from django.conf.urls import url
from myapp import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^about/$',views.about, name='about'),
        url(r'^(?P<course_No>\d+)/$', views.detail, name='detail'),
        url(r'^addtopic/$',views.addtopic, name='addtopic'),
        url(r'^topics/$',views.topics, name='topics'),
        url(r'^topics/(?P<topic_id>.*)/$', views.topicdetail, name='topicdetail'),
        url(r'^register/$',views.register,name='register'),
        url(r'^login/$',views.user_login, name='login'),
        url(r'^logout/$',views.user_logout,name='logout'),
        url(r'^mycourse/$', views.mycourse, name='mycourse'),
        url(r'^forgetpasswork/$', views.fotgetPassword, name= 'forgetpassword')

]

myapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator,MinValueValidator

class Author(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    birthdate = models.DateField()
    city = models.CharField(max_length=50,blank=True)
    nationality=models.CharField(max_length=50,null=True,blank=True)

    def __str__(self):
        return ('%s %s' % (self.firstname,self.lastname))


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author)
    in_stock = models.BooleanField(default=True)
    numpage = models.IntegerField(default=0, validators=[MaxValueValidator(1000),MinValueValidator(50)])

    def __str__(self):
        return self.title


class Student(User):
    PROVINCE_CHOICES = (
        ('AB','Alberta'), # First value is stored in db, the second is descriptive
        ('MB', 'Manitoba'),
        ('ON', 'Ontario'),
        ('QC', 'Quebec'),
    )
    address = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province=models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    age = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.username


class Course(models.Model):
    course_no=models.IntegerField(primary_key=True)
    title=models.CharField(max_length=50)
    textbook=models.ForeignKey(Book)
    students=models.ManyToManyField(Student, blank=True)

    def __str__(self):
        return self.title


class Topic(models.Model):
    subject = models.CharField(max_length=100, unique=True)
    intro_course = models.BooleanField(default=True)
    NO_PREFERENCE = 0
    MORNING = 1
    AFTERNOON = 2
    EVENING = 3
    TIME_CHOICES = (
        (0, 'No preference'),
        (1, 'Morning'),
        (2, 'Afternoon'),
        (3, 'Evening')
    )
    time = models.IntegerField(default=0, choices=TIME_CHOICES)
    num_responses = models.IntegerField(default=0)
    avg_age = models.IntegerField(default=20)

    def __str__(self):
        return self.subject

myapp/forms.py
from django import forms
from myapp.models import Topic

class TopicForm(forms.ModelForm):
    class Meta:
        model= Topic
        fields = {"subject","intro_course","time","avg_age"}
        widgets = {"time":forms.RadioSelect()}
        labels = {"intro_course":'This should be an introductory level course',"time":u'Preferred Time','avg_age':u'What is your age?'}

class InterestForm(forms.Form):
    interest = forms.TypedChoiceField(widget=forms.RadioSelect,choices=((1,'Yes'),(0,"No")))
    age = forms.IntegerField(label='Age',initial=20)
    comment = forms.CharField(widget=forms.Textarea(),label='Additional Comments',required=False,)

myapp/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from myapp.models import Author, Book, Course, Topic, Student
from myapp.forms import *
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


# Create your views here.

def index(request):
    courselist = Course.objects.all().order_by('title')[:10]
    return render(request, 'myapp/index.html', {'courselist': courselist})


def about(request):
    return render(request, 'myapp/about.html')


def detail(request, course_No):
    get_object_or_404(Course, course_no=course_No)
    course = Course.objects.get(course_no=course_No)
    return render(request, 'myapp/detail.html', {'course': course})


def topics(request):
    topiclist = Topic.objects.all()
    return render(request, 'myapp/topics.html', {'topiclist': topiclist})


def addtopic(request):
    topiclist = Topic.objects.all()
    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.num_responses =+ 1
            topic.save()
            return HttpResponseRedirect(reverse('myapp:topics'))
    else:
        form = TopicForm()
    return render(request, 'myapp/addtopic.html', {'form': form, 'topiclist': topiclist})

def topicdetail(request, topic_id):
    get_object_or_404(Topic, subject=topic_id)
    topic = Topic.objects.get(subject=topic_id)
    if request.method == 'POST':
        form = InterestForm(request.POST)
        if form.is_valid():
            interest = form.cleaned_data['interest']
            age = form.cleaned_data['age']
            topic.avg_age = (topic.num_responses * topic.avg_age + age) / (topic.num_responses + 1)
            if interest:
                topic.num_responses = +1
                topic.save()
        return HttpResponseRedirect(reverse('myapp:topics'))
    else:
        form = InterestForm()
        return render(request, 'myapp/topicdetail.html', {'topic': topic, 'form': form})

def register(request):
    if request.method=='POST':
        username=request.POST['Username']
        password=request.POST['Password1']
        password2=request.POST['Password2']
        firstname=request.POST['Firstname']
        lastname = request.POST['Lastname']
        email = request.POST['Email']
        if password!=password2:
            return HttpResponse('Password not match!')
        elif password==password2:
            Student.objects.create_user(username=username,password=password,first_name=firstname,last_name=lastname,email=email)
            return HttpResponseRedirect(reverse('myapp:login'))
    else:
        return render(request,'myapp/register.html')

def user_login(request):
    if request.method == 'POST':
        username = request.POST['Username']
        password = request.POST['Password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('myapp:index')) #
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse(('myapp:index')))

@login_required()
def mycourse(request):
    try:
        Student.objects.get(username=request.user)
        course=Course.objects.filter(students__username=request.user)
        return render(request, 'myapp/mycourse.html',{'user':request.user,'course':course})
    except:
        return HttpResponse('You are not a student!')
    return render(request,'myapp/mycourse.html')

def fotgetPassword(request):
    try:
        pass
    except:
        return render(request,'myapp/ForgetPassword.html')
    return render(request, 'myapp/ForgetPassword.html')

    '''
if request.method=='POST':
        form = InterestForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            interest=form.cleaned_data['interest']
            age=form.cleaned_data['age']
            topic.avg_age = (topic.num_responses*topic.avg_age+age)/(topic.num_responses+1)
            if interest:
                topic.num_responses=+1
                topic.save()
            return HttpResponseRedirect("/topics/page")
    else:
        form=InterestForm()
    return render(request, 'myapp/topicdetail.html', {'topic':topic,'form':form})


def index(request):
    courselist = Course.objects.all() [:10]
    response = HttpResponse()
    heading1 = '<p>' + 'List of courses: ' + '</p>'
    response.write(heading1)
    for course in courselist:
        para = '<p>' + str(course) + '\t-- Course No.'+ str(course.course_no) + '</p>'
        response.write(para)
    authorlist = Author.objects.all().order_by('-birthdate')[:5]
    heading2 = '<p>' + 'List of Authors: ' + '</p >'
    response.write(heading2)
    for author in authorlist:
        para = '<p>' + str(author) + '\t-- Birthdate: ' + str(author.birthdate)+ '</p >'
        response.write(para)
    return response


def about(request):
    response=HttpResponse()
    text='<p>'+'This is a Course Listing APP'+'</p>'
    response.write(text)
    return response
    
def detail(request, course_No):
    response=HttpResponse()
    get_object_or_404(Course, course_no=course_No)
    str1='<p>' + 'Information of courses: ' + '</p>'
    response.write(str1)
    course=Course.objects.filter(course_no=course_No)
    for i in course:
        response.write("<p>" + str(i) + "</p>")
        response.write("<p>" + "Course Numver: " + str(course_No) + "</p>")
        response.write("<p>" + "TextBook: " + str(i.textbook) + "</p>")
    return response
'''

myapp/templates/myapp/ForgetPassword.html
<!DOCTYPE html>
{% load staticfiles %}
<html >
<head>
  <meta charset="UTF-8">
  <title>Retrieve Your Password</title>
  <link rel="stylesheet" type="text/css" href="{% static 'myapp/login.css'%}" >
</head>

<body>
<div class="container">
	<section id="content">
		<form action="{% url 'myapp:forgetpassword'%}" method='POST'>
            {% csrf_token %}
            <h1>Retrieve Your Password</h1>
			<div>
				<input type="text" placeholder="Username" required="" name="Username" />
			</div>
			<div>
				<input type="emal" placeholder="Email Address" required="" name="Email" />
			</div>
            <div>
				<input type="submit" value="Submit" />
				<a href={% url 'myapp:register' %}>Register</a>
                <a href="{% url 'myapp:login' %}">Log in</a>
			</div>
		</form><!-- form -->
		<div class="button">

		</div><!-- button -->
	</section><!-- content -->
</div><!-- container -->
</body>
</html>

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <body>
        <p>This is a Course Listing APP</p>
        <p><a href="{% url 'myapp:index' %}">Back</a></p>
    </body>
{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About This Website</title>
</head>
<body>
    <p>This is a Course Listing APP</p>
    <p><a href="{% url 'myapp:index' %}">Back</a></p>
</body>
</html>

myapp/templates/myapp/addtopic.html
{% extends 'myapp/base.html' %}

{% block body_block %}
<body>
    <form action='{% url 'myapp:addtopic' %}' method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    </form>
</body>
</html>
{% endblock %}

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head>
      <!--  <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" /> disable CSS style-->
        <title>Course Listing APP - {% block title %}Welcome!{% endblock %}</title>
    </head>

    <body>
        <div>
            <h1>{% block myhdg %}
                    {% if request.user.is_authenticated %}
                        Hello {{ request.user.first_name }}    <a style="font-size:small" href="{% url 'myapp:logout' %}">Log Out</a>
                        <a style="font-size:small" href="{% url 'myapp:mycourse' %}">My Course</a>
                    {% else %}
                        <div style="font-size:small"> <a href="{% url 'myapp:register' %}">Sign up</a> OR  <a href="{% url 'myapp:login' %}">Log in</a></div>
                        You have not logged in your account.
                    {% endif %}
                    {% endblock %}
            </h1>
            {% block body_block %}*** {% endblock %}
        </div>
        <hr />
        <div>
            <li>
                <li class="hbar1"><a href = "{% url 'myapp:index' %}">Main Page</a></li>
                <li class="hbar1"><a href="/myapp/about/">About This Site</a></li>
            </ul>
        </div>
    </body>
</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block body_block %}
<body>
    <h2>Details of Course</h2>
    <p><b>Course Number:</b> {{ course.course_no }}</p>
    <p><b>Course Title:</b> {{ course.title }}</p>
    <p><b>Textbook:</b> {{ course.textbook }}</p>
    <br>
    <p><a href="{% url 'myapp:index' %}">Back</a></p>

</body>
{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ course.title }}</title>
</head>
<body>
<br>
    <h2>Details of Course</h2>
    <p><b>Course Number:</b> {{ course.course_no }}</p>
    <p><b>Course Title:</b> {{ course.title }}</p>
    <p><b>Textbook:</b> {{ course.textbook }}</p>
    <br>
    <p><a href="{% url 'myapp:index' %}">Back</a></p>

</body>
</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <body>
    {% if courselist %}
        <h2>List of Courses </h2>
        <ol>
            {% for course  in courselist %}
                <li> <a href="{% url 'myapp:detail' course.course_no%}">{{ course.title}}</a> </li>
            {% endfor %}
        </ol>
        <h2><a href="{% url 'myapp:topics' %}">Topics</a></h2>
    {% else %}
        <strong>There are no avail able courses!</strong>
    {% endif %}
    </body>
{% endblock %}

myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Course Listing APP</title>
</head>

<body>
    {% if courselist %}
        <h2>List of Courses</h2>
        <ol>
            {% for course  in courselist %}
                <li> <a href="{% url 'myapp:detail' course.course_no%}">{{ course.title}}</a> </li>
            {% endfor %}
        </ol>

    {% else %}
        <strong>There are no avail able courses!</strong>
    {% endif %}
    <p><a href="{% url 'myapp:about' %}">About page</a></p>
</body>
</html>

myapp/templates/myapp/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html >
<head>
  <meta charset="UTF-8">
  <title>Login</title>
  <link rel="stylesheet" type="text/css" href="{% static 'myapp/login.css'%}" >
</head>

<body>
<div class="container">
	<section id="content">
		<form action="{% url 'myapp:login'%}" method='POST'>
            {% csrf_token %}
            <h1>Login</h1>
			<div>
				<input type="text" placeholder="Username" required="" name="Username" />
			</div>
			<div>
				<input type="password" placeholder="Password" required="" name="Password" />
			</div>
            <div>
				<input type="submit" value="Log in" />
				<a href={% url 'myapp:forgetpassword' %}>Lost your password?</a>
				<a href={% url 'myapp:register' %}>Register</a>
			</div>
		</form><!-- form -->
		<div class="button">

		</div><!-- button -->
	</section><!-- content -->
</div><!-- container -->
</body>
</html>

myapp/templates/myapp/mycourse.html
{% extends 'myapp/base.html' %}

{% block body_block %}
<body>
    <h2>My Course</h2>
    <ol>
    {% for a in course %}
        <li>{{ a.title }}</li>
    {% endfor %}
     </ol>
    <p><a href="{% url 'myapp:index' %}">Back</a></p>

</body>
{% endblock %}

myapp/templates/myapp/register.html
<!DOCTYPE html>
{% load staticfiles %}
<html >
<head>
  <meta charset="UTF-8">
  <title>Register</title>
  <link rel="stylesheet" type="text/css" href="{% static 'myapp/login.css'%}" >
</head>

<body>
<div class="container">
	<section id="content">
		<form action="{% url 'myapp:register'%}" method='POST'>
            {% csrf_token %}
            <h1>Sign Up</h1>
			<div>
				<input type="text" placeholder="Username" required="" name="Username" />
			</div>
            <div>
				<input type="text" placeholder="First Name" required="" name="Firstname" />
			</div>
            <div>
				<input type="text" placeholder="Last Name" required="" name="Lastname" />
			</div>
			<div>
				<input type="password" placeholder="Password" required="" name="Password1" />
			</div>
            <div>
				<input type="password" placeholder="Password Again" required="" name="Password2" />
			</div>
            <div>
				<input type="emal" placeholder="Email Address" required="" name="Email" />
			</div>
            <div>
				<input type="submit" value="Register" />
				<a href={% url 'myapp:forgetpassword' %}>Lost your password?</a>
				<a href="{% url 'myapp:login' %}">Log in</a>
			</div>
		</form><!-- form -->
		<div class="button">

		</div><!-- button -->
	</section><!-- content -->
</div><!-- container -->
</body>
</html>

myapp/templates/myapp/topicdetail.html
{% extends 'myapp/base.html' %}

{% block body_block %}
<body>
    <h2>Details of Topic</h2>
    <p><b>Subject Name: </b>{{ topic.subject }}
    {% if topic.intro_course %}
        --an introductory course</p>
    {% else %}
        --not an introductory course</p>
    {% endif %}
    <p>As of now, <b>{{ topic.num_responses}}</b> students are intrested in this topic. </p>
    <p>The average age of people interested in the particular topic is <b>{{ topic.avg_age }}</b></p>

    <form action="{% url 'myapp:topicdetail' topic.subject%}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    </form>
    <br>
    <p><a href="{% url 'myapp:topics' %}">Back</a></p>
</body>
{% endblock %}

myapp/templates/myapp/topics.html
{% extends 'myapp/base.html' %}

{% block body_block %}
<body>
{% if topiclist %}
        <h2>List of Topics</h2>
        <ol>
            {% for topic  in topiclist %}
                <li> <a href="{% url 'myapp:topicdetail' topic.subject%}">{{ topic.subject}}</a> </li>
            {% endfor %}
        </ol>

    {% else %}
        <strong>There are no avail able courses!</strong>
    {% endif %}
</body>
{% endblock %}